### ISSUE TITLE
Solve the duplicated item-descriptions repo

### ISSUE THREAD

**Issue by rsmith013** [cedadev/search-futures#110]
item-descriptions are published in two places:
- [github](https://github.com/cedadev/item-descriptions)
- [gitlab](https://breezy.badc.rl.ac.uk/stac/stac-item-descriptions)

The github version is so they are public and can be used as an example, the gitlab version is to feed the CI.

The CI pipeline turns the gitlab version into a container. This is used by the stac-indexer-deploy repo as an init-container to copy the item-descriptions in to feed the generators. This means that when a change is made to master in the gitlab item-descriptions, it automatically updates the live indexing operation. We would then want to add a step onto the end of the [stac-indexer-deploy](https://breezy.badc.rl.ac.uk/stac/stac-indexer-deploy) pipeline to trigger adding messages to the queue for any affected paths.

Update item-descriptions --> rebuild and deploy generators --> trigger check to rescan changed assets

An example of a similar workflow can be seen:
- [cci_tagger_json](https://breezy.badc.rl.ac.uk/rsmith013/cci_tagger_json) --> Item-descriptions
- [rabbit-indexer-deploy](https://breezy.badc.rl.ac.uk/rsmith013/rabbit-indexer-deploy) (the facet indexer) --> stac-indexer-deploy

The process of feeding back into the queue is based on merge requests. An example shown in [cci_tagger_json](https://breezy.badc.rl.ac.uk/rsmith013/cci_tagger_json).

It is probably the best cause of action to archive the public github version and just use the gitlab version. It will reduce confusion, having things in one place and gitlab can make use of all the automation features.

This just means that the Documentation for the asset scanner has to be up to date so that external users can read about how the descriptions are constructed.

**Comment by agstephens** [comment]
Duplicated.
