### ISSUE TITLE
Review and modify (if needed) the "stac-asset-spec"

### ISSUE THREAD

**Issue by agstephens** [cedadev/search-futures#112]
See: https://github.com/cedadev/stac-asset-spec

- [x] @rhysrevans3 review
- [x] @Mahir-Sparkess review
- [x] @agstephens review

**Comment by Mahir-Sparkess** [comment]
~~The `type` attribute for assets is required to be "Feature", that's the same as item. I think the `type` should be something else along the lines of "Asset".
Collection has the `type` set as "Collection" so my interpretation of the `type` field is to distinguish more explicitly if this object is Item, Catalog, Collection.~~

Ignore me, I had a look at what GeoJSON was and what was meant by Feature and FeatureCollection
