### ISSUE TITLE
Build a spreadsheet for the ESGF mapping from SOLR to STAC

### ISSUE THREAD

**Issue by agstephens** [cedadev/search-futures#115]
- Tab 1: CMIP6 Dataset (Item)
- Tab 2: CMIP6 File (Asset)

We might want separate CMIP5 tabs as well - but hopefully not.

**Comment by agstephens** [comment]
Refer to table 2 in the ESGF Future Architectures:
 https://zenodo.org/record/3928223

Two points to consider:
1. Can we remove some metadata/properties?
2. Are there some properties we should add?

To consider:
- Schema.org tags:
  - Refer to Google dataset search: https://datasetsearch.research.google.com/search
  - What else might we want to tag? Are there any NERC standards for this?
- ES-Doc content
  - Is there any utility in pulling in ES-Doc content? Rather than including links out to ES-Doc?
- date/time object for temporal search
- Bounding box (geospatial constraints)
- DOI (Citation) 1..n:
  - unlikely that Item or Asset has a unique DOI - they live at _model_ or _experiment_ level
- Errata content:
  - maybe we would link in the user interface rather than in the catalogue

**Comment by Mahir-Sparkess** [comment]
Working version: https://docs.google.com/spreadsheets/d/1eGB09gkLRM0OQw6trAKkVC0SaVE4EgJt-z_T1DM-X18/edit?usp=sharing

Some mappings from ESGF Solr to STAC for dataset/items and file/assets.

**Comment by agstephens** [comment]
Suggested columns for each sheet:
- Solr: Key
- Solr: Type
- Solr: Example value
- Solr: Comment - e.g. for "internal" Solr fields
- STAC: Key
- STAC: Type
- STAC: Example value
- STAC: Comment
