### ISSUE TITLE
Let's submit a lightning talk to the Cloud-Native Geospatial Outreach Day

### ISSUE THREAD

**Issue by agstephens** [cedadev/search-futures#120]
Details:
- Info: https://medium.com/radiant-earth-insights/save-the-date-cloud-native-geospatial-outreach-event-on-april-19-20-ef4e396e1053
- Form to express interest: https://docs.google.com/forms/d/e/1FAIpQLSe2iKvsMm8vYDso2L1IDQki4xIAdKyB8nUbqz8Kz95oCFkokQ/viewform?pli=1

**Comment by agstephens** [comment]
@Mahir-Sparkess and @rhysrevans3: let's discuss this. It might be a great opportunity for one of you to present.

**Comment by agstephens** [comment]
@rhysrevans3 , why not draft an abstract here for us to discuss? And then sign up and submit it.

**Comment by rhysrevans3** [comment]
### Draft abstract:

CEDA is a national data centre for atmospheric and earth observation research. We host over 15 Petabytes of atmospheric and earth observation data from a range of different sources, include aircraft campaigns, satellites, automatic weather stations, and climate models, amongst many more. Although there are data standards, these standards vary through time and across different domains. This leads to a heterogeneous archive with legacy formats and structures, presenting an indexing problem.

Our goal was to produce a service that allowed search across the archive. This standard would need to be flexible enough to meet the different data formats within the archive, while being specific enough to allow for faceted and free text search. Additionally, given the size and growth rate of the CEDA archive it would need to be scaleable. We were interested to see if STAC could meet our needs and have begun designing a full stack implementation. This has lead to the creation of generators to build the STAC indexes, an elasticsearch backed API, and web and python clients.

**Comment by agstephens** [comment]
Hi @rhysrevans3, looks like a good first go. Could you put it into a Google Doc and then it'll much easier for others to make suggestions and comment. Thanks

**Comment by rhysrevans3** [comment]
https://docs.google.com/document/d/171fVfvD8XjiXLJtINVRUdv9IgYLjCuIKdU21n7gYGzw/edit?usp=sharing
