### ISSUE TITLE
Get some example datasets in the archive which are a little messy

### ISSUE THREAD

**Issue by rsmith013** [cedadev/search-futures#14]
- 1 example you can extract
- 1 example you can't
- 1 highly faceted

something old, something new, something borrowed, something blue

**Comment by gap736uk** [comment]
List prepared here:

https://docs.google.com/spreadsheets/d/1-O28u3NwqVkP-6xkrwa2fSPht00qexn7kwfu_4kcQ54/edit#gid=0

This has a list of paths which v likely at the MOLES dataset level. 

The entries have also been annotated to indicate if there are likely to be facet info available from :
 
- path
- filename
-  internal metadata

Also annotated with format info and other notes.

**Comment by gap736uk** [comment]
Note - need to add in some more examples from EO side of things - esp satellite examples.

**Comment by gap736uk** [comment]
@rsmith013  - I'm closing this issue off as we now have Sat sample paths too, so I think this might be enough for you at this stage. Feel free to re-open if there are others that you need in the future.
