### ISSUE TITLE
Are all files in an item assets? 

### ISSUE THREAD

**Issue by rsmith013** [cedadev/search-futures#15]
Do we need to make the distinction between data files, metadata files, and quicklooks?

**Comment by gap736uk** [comment]
directory structure convention that applies in most places in the archive:

https://ceda-internal.helpscoutdocs.com/article/4158-ceda-archive-structure-model#gsc.tab=0

**Comment by rsmith013** [comment]
Will see how it shakes out, but STAC assets have a `role` attribute which will differentiate between the different file types
