### ISSUE TITLE
Should we rename the asset-scanner?

### ISSUE THREAD

**Issue by rhysrevans3** [cedadev/search-futures#155]
### Reason

The asset scanner has morphed into a more general purpose scanner and with the planned description changes it will move further from this name.

### Possible alternate names:
 - stac-builder
 - stac-creator
 - stac-architect
 - stac-constructor
 - stac-author
 - stac-designer
 - stac-scanner
 - stac-generator
 - stac-spawner
 - stac-producer

**Note**: Some of these may already exist elsewhere.

**Comment by Mahir-Sparkess** [comment]
my votes: 
- stac-generator
- stac-scanner

**Comment by agstephens** [comment]
I would go for: `stac-generator`
