### ISSUE TITLE
Archive Manager Story

### ISSUE THREAD

**Issue by gap736uk** [cedadev/search-futures#39]
Title: Archive Manager Story
-----
**As an** Archive Manager responsible for the overall archive, 
**I want** to be able to check against a list of assets and their attributes in order to manage the archiving of data in the CEDA archive, 
**so that I can** <achieve some goal>.

**to capture**
Storage stories
***migration*** 
- this is about moving copies of assets
Need to have a big list of all assets on one media instance (e.g. specific Quobyte volume) to support migration to alternative storage. For this the list needs to be processed and able to reference back to the assets to establish which have been copied and which remain to be copied. Finally, need to establish which asset instance is the live one to use for end-user distribution and track removal of old asset instance and retirement of underlying media. Error tracking is essential to this process - for this the following are required. Need to know:
 - when the process fell over
 - need to know when the process happened cleanly to full completion.

***duplication***
 - this is about having an additional copy of a part of the archive ('chunk') to present as an exact replica. To do this I need to convert the 'chunk' list into a list of assets. Then copy these assets to the required duplication destination and knowing where and when the content of the source 'chunk' has changed to enable subsequent duplications to destination  - this will include modification to specific assets and additions and deletions to the overall 'chunk'. Also need to tag which asset instance is available for end-user distribution.

***switching primary storage location***
 - Given two or more copies of an asset or 'chunk' (i.e. list of assets)  apply flagging to assets to identify which is the 'primary' (i.e. live instance) for end-user access and which are alternative instances and to have the ability to swap these flags around as required to support changes of use.
  
***backup***
 - as for duplicates EXCEPT modified copies, deletions will be maintained. Need to identify which asset instances would be primarily available for retrieval as the principal copy of the asset but itself is not already principal asset instance). (NOTE, presently out of scope are identifying when off-site back-ups exist).

***fixity management***

***manage data deposit***
 - Need a system where an asset is added/removed/modified within the archive to permit a complete list of all archive assets. It is essential that this is a complete and accurate list of the archive as possible.
 
***data distribution management***

Acceptance Criteria
--------------------

* Core requirements*
** Chunk Determination**
An underpinning function is determining a pattern into a workable list of assets - this may be based on a range of facets such as:
 - by logical path pattern
 - by storage media identity
 - file/asset size
 - modification time
 - creation time
 - asset internally derived metadata (e.g. valid time, geolocation, processing level, variable etc etc.)

** Identify primary instance of an asset which is available for end-user to access (actual access mechanism not covered)**
** identify asset instances which are NOT primary end-user accessible assets , but primarily flagged for retrieval from non-live access (e.g. tape/back-up)**

-------------------

Scenario A: symlinked data (e.g. CMIP5/6) 
Given that <some context>, 
when <some action is done>, 
then <such outcomes are expected to occur>.Stretch Goals
--------------
<optional>Notes
-----
<optional>Priority: <Highest, High, Medium, Low, Lowest, Unprioritized>Story Points: <1, 3, 5, 8, 13, 21, ... >

**Comment by spepler** [comment]
Need to write this more like a use case.

**Comment by gap736uk** [comment]
Hi Sam...

We should sit down and put this together.. and we'll capture the use-cases

**Comment by gap736uk** [comment]
Yet to capture some how...
 - catalogue coverage completeness
 - discovery metadata completeness (e.g. licence for all data, missing geo-temporal info, parameters etc)
 - data providence and permission to handle etc.
 - metadata origins (e.g. from file, from CMMS)

**Comment by spepler** [comment]
This is to old. Bin
