### ISSUE TITLE
enable collection of extra facets e.g permitted use

### ISSUE THREAD

**Issue by rsmith013** [cedadev/search-futures#69]

**Comment by Mahir-Sparkess** [comment]
https://github.com/cedadev/asset-scanner/pull/15

https://github.com/cedadev/collection-generator/pull/1

**Comment by Mahir-Sparkess** [comment]
- [ ] Add search facets to item descriptions
- [ ] Test the description correctly merges the facets together
- [ ] Add search facet to ItemDescription properties and handle incase of None.
- [ ] Edit item validator for new search facet list.
