### ISSUE TITLE
- templates for item titles (could be a DRS templated from facets)

### ISSUE THREAD

**Issue by rsmith013** [cedadev/search-futures#71]
This is about enabling people to write temples for item titles and descriptions. 

Relevant repos:
[Asset Scanner](https://github.com/cedadev/asset-scanner/tree/master/asset_scanner)
[Item Descriptions](https://github.com/cedadev/item-descriptions/tree/master/descriptions)
[Item Generator](https://github.com/cedadev/item-generator)

Changes required:
- [x] Add a `templates` section to item-descriptions (title_template, description_template). The section may not exist and one or the other key may not exist.
- [x]  Add a property to the `ItemDescription` class in asset-scanner to access this new field.
- [x] If there are templates, render those templates and add the keys 'properties.title' and `properties.description` to the output description. e.g. ```{"properties": {"title": "Rendered item title"}}```

**Comment by Mahir-Sparkess** [comment]
Asset-scanner-example title and description template: 
- https://github.com/cedadev/asset-scanner-example/pull/1

Item_Descriptions properties for template title and description:
- https://github.com/cedadev/asset-scanner/pull/18

Generate the templating title and description to output:
- https://github.com/cedadev/item-generator/pull/43

Add template title and description to item validator schema:
- https://github.com/cedadev/item_description_validator/pull/5
