### ISSUE TITLE
Check to see if we can now use the upstream stac-fastapi repo.

### ISSUE THREAD

**Issue by rsmith013** [cedadev/search-futures#77]
Our latest changes have been merged into https://github.com/stac-utils/stac-fastapi

It would be good if we could get off our own fork. Could try to ease the pain by making a branch of the dev branch in stac-fastapi-elasticsearch (the branch we are currently running from) and merging upstream master into this branch. Then once that works install just the upstream and see if anything else breaks?

- [x] Make a branch of stac-fastapi-elasticsearch
- [x] install the requirements
- [x] install the upstream stac-fastapi
- [x] See what breaks and see if it can be fixed by local only changes

**Comment by Mahir-Sparkess** [comment]
https://github.com/cedadev/stac-fastapi-elasticsearch/pull/29
seems to work

**Comment by rsmith013** [comment]
completed and deployed
