### ISSUE TITLE
Look at STAC query spec and see how it could be extended, replaced to provide faceted search

### ISSUE THREAD

**Issue by rsmith013** [cedadev/search-futures#9]
https://github.com/radiantearth/stac-api-spec/blob/master/item-search/README.md#query

**Comment by philipkershaw** [comment]
@rsmith013 pls forward the link to Ryan :)

**Comment by rsmith013** [comment]
https://github.com/radiantearth/stac-api-spec/blob/dev/fragments/filter/README.md

**Comment by rsmith013** [comment]
It looks like the hard work has already been done. The query extension to the STAC api-spec is deprecated in order to follow the OGC CQL (Common Query Language) and there is a filter extension on the dev branch of the api-spec which details how this would work: https://github.com/radiantearth/stac-api-spec/blob/dev/fragments/filter/README.md

It looks to me like this is exactly what we are after:
/queryables – returns the list of available facets for searching and each facets json-schema document can expose the acceptable values to UIs
 
/queryables is available at both the root level, individual collection and there is growing support for a cross collection implementation (akin to the opensearch description document where all “queryables” are available and are restricted as your search restricts) https://github.com/opengeospatial/ogcapi-features/issues/576
 
Saves us re-inventing the wheel!
